### ISSUE TITLE
Readme.md usage example causes Unsupported Operation Exception

### ISSUE THREAD

**Issue by ameron32** [AlexKolpa/fab-toolbar#1]
In usage example, this line of XML code causes the mentioned exception:

```
tb:tb_animation_duration="500"
```

when converted to the following due to attribute name mismatch
    tb:tb_anim_duration="500"
causes the following exception
    java.lang.UnsupportedOperationException: Can't convert to integer: type=0x4
            at android.content.res.TypedArray.getInteger(TypedArray.java:367)
            at com.github.alexkolpa.fabtoolbar.FabToolbar.loadAttributes(FabToolbar.java:67)

Added to build.gradle as follows:

dependencies {
...
  compile 'com.github.alexkolpa:floating-action-button-toolbar:0.5.0'
...
}

In library:
   attrs.xml appears to define tb_anim_duration as float.
   in FabToolbar.java, TypedArray.getInteger() is called.

Suggested fix:
   please change attrs.xml > tb_anim_duration to "integer"

**Comment by AlexKolpa** [comment]
Can't believe I missed that one! Thanks for reporting. I've uploaded a new version to maven which should be available soon!
